
/**
* ServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Monday, June 9, 2014 4:32:46 PM ICT
*/


// A very simple interface to explain this example
public interface ServiceOperations 
{
  void ping ();
  String hello (String mesg);
} // interface ServiceOperations
